name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Check existing release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "$(gh release view --repo ${{ github.repository }} ${{ needs.build.outputs.version }} 2>&1)" != 'release not found' ]; then
            echo "Release already exists"
            exit 1
          fi

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.version }}
          draft: true
          files: |
            Artifacts/*
