name: Test
on:
  push:
    # branches:
    #   - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup repository
        run: |
          mkdir .github/ProjectRoot/Packages/dev.paltee.avatar-aid -p
          mv * .github/ProjectRoot/Packages/dev.paltee.avatar-aid

      - uses: anatawa12/sh-actions/resolve-vpm-packages@master
        with:
          project-path: .github/ProjectRoot
          repos: |
            https://vpm.nadena.dev/vpm-prerelease.json

      - uses: actions/cache@v4
        with:
          path: .github/ProjectRoot/Library
          key: Library-${{ hashFiles('.github/ProjectRoot/Packages/*.json') }}
          restore-keys: Library-

      - uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2022.3.22f1
          testMode: EditMode
          projectPath: .github/ProjectRoot
          githubToken: ${{ secrets.GITHUB_TOKEN }}
